### ISSUE TITLE
Selecting with one class out of several

### ISSUE THREAD

**Issue by goderich** [jbclements/sxml#8]
First of all, thank you for the wonderful package. I've been doing some web scraping recently and it's working great.

However, there's one issue that I haven't been able to find an answer to. When there is an HTML element with two or more classes (e.g. `<div class="a b">`, if I want to select/find that element, I have to put all the classes in my query, like so:

`((sxpath '(// (div (@ (equal? (class "a b")))))) html)`

Searching just for `(equal? (class "a"))` doesn't work (perhaps understandably so, if it's testing for strict equality between strings). This is in contrast to python's bs4 library, which will select the example div if I search for `(class_="a")`.

Is there a function or selector in sxml that does what I want?

**Comment by jbclements** [comment]
Whoa... that sounds like a significant extension of the "class" mechanism; is that recognized by any xml standards?

To actually answer your question: I'm not aware of a way to do that, but I wouldn't be surprised to find a way to splice an arbitrary predicate into a query; an "unquote" mechanism of some kind.

I should be clear: I'm not the author of this code; I've used it a number of times, but it's definitely not "my code"... or even Racket code; its scheme roots are still very evident. You might want to ask Kirill Lisovsky, Dmitry Lizorkin, or Oleg himself.

**Comment by goderich** [comment]
>I'm not the author of this code

Oh I see. But you are the maintainer of the Racket library, correct?

>Whoa... that sounds like a significant extension of the "class" mechanism; is that recognized by any xml standards?

I don't actually know any standards, I'm just a guy doing some scraping. I've used Python for that before, and while it's all stringly typed, the Beatiful Soup library has a pretty decent API. I don't know if my expectations from using bs4 are unrealistic or nonstandard.

Do you have an idea of where in the library I could start looking? I could also try implementing this functionality by myself, if it's not included.

**Comment by yilinwei** [comment]
@jbclements

It is recognised by CSS at the very least — which is presumably why HTML slurping
libraries support it.

Snippets to demonstrate behaviour. I couldn't find a sharing service which doesn't require
a sign in so I've copied them below.

```html
<p class="first second">Foo</p>
```

```css
.first {
  color: red
}
.second {
  font-size: 21px
}
```

**Comment by jbclements** [comment]
So, I did a bit of digging this morning, and it looks to me like you can do this, with custom predicates. I've added this to the sxpath docs, but it will probably take a day or two for those to be available via pkgs.racket-lang.org, so I'll paste them here. It's going to look gross because it's formatted for scribble and not markdown, sorry.

```
@section{Custom Predicates}

If you take a look at the expansion above, you'll see that you can
directly embed procedures (essentially a "3D syntax" approach) into
sxpath terms, to provide more customizable matching. However, you'll
be hard-pressed to find out exactly what the interface to those procedures
looks like. I've done some experimentation and some light code-reading,
and it @emph{appears} to me that such procedures are called with two
arguments; a list of nodes, and another list ... of ... variable bindings?
I realize that it's uncommon for documentation to be so wishy-washy,
but I'm erring on the side of getting the information out there.

Anyhow, suppose (just for instance) that you wanted to be able to use
sxpath to find divs with a particular classname (e.g. @racket[zzz]),
 but that—like CSS—you wanted
to treat the value of the "class" property as being a space-separated
list of class names, so what you're really looking for is a node whose
class property contains @racket["zzz"] as part of a space-separated
list, for instance @racket["yyy zzz aaa"].

Can you do this? Yes you can! Here's some example code:

@codeblock|{
;; an sxpath matcher for "class" nodes with the given classname
;; as part of its space-separated list
(define ((class-str-includes? classname) nodes vars-thingy)
  (ormap (node-with-class-str classname) nodes))

;; is this a node named "class" with the given classname as
;; part of its space-separated list?
(define ((node-with-class-str classname) node)
  (match node
    [(list 'class (? string? classnames-str))
     (member classname
             (map string-trim (regexp-split #px" " classnames-str)))]))

((sxpath `(// abc (z (@ class ,(class-str-includes? "bar")))))
 '(*TOP* (x (x (x (abc (y (x))))
               (abc (z (@ (class "bar tar")) (x) "blorg"))
               (abc (z (@ (class "car bar")) (x) "blorg3"))
               (abc (z (@ (class "baz car")) (x) "blorg2"))))))
}|

There are several clunky things about this solution; it's clunky that I
repeat "class" in two different places, but abstracting over this would
probably naturally soak up the @"@" as well, and I wasn't sure I wanted
to do that. Also, I was surprised to see that the class node was actually
passed to the matcher, rather than its content. But sure, okay. Also,
the name @racket[vars-thingy] should strongly suggest that I'm not entirely
sure what's going on here.

As before: pull requests welcome!
```

**Comment by jbclements** [comment]
Okay to close this issue?

**Comment by goderich** [comment]
Thank you! I'll try this out, and close the issue now.

**Comment by jbclements** [comment]
BTW, if you run into problems with this, let me know; there are several aspects of this that I'm unsure of, and problems you encounter might help me improve the documentation.

Thanks!
